### ISSUE TITLE
If have columns without data search failed

### ISSUE THREAD

**Issue by hardenchant** [izimobil/django-rest-framework-datatables#21] opened 2018-08-14 10:36 UTC
I have this:
```
columns: [
            {
                "className": 'details-control',
                "orderable": false,
                "data": null,
                "defaultContent": '<a class="fa fa-info-circle">'

            }
]
```
for hide\open menu under the row. And its data=null field. Search not working in this case.

**Comment by izimobil** [comment] 2018-08-16 13:33
I don't reproduce your issue, I just added your snippet to the [example](https://github.com/izimobil/django-rest-framework-datatables/blob/master/example/albums/templates/albums/albums.html) project, and search is working perfectly.

**Comment by izimobil** [comment] 2018-12-05 11:45
Closing this issue because there is no feedback.

**Closed by izimobil** 2018-12-05 11:45 UTC
Labels: Feedback requested
