### ISSUE TITLE
Fail when using SQL query 'RawQuerySet' object has no attribute 'count'

### ISSUE THREAD

**Issue by PiotrKrosniak** [izimobil/django-rest-framework-datatables#134] opened 2022-09-23 15:25 UTC
```
Request Method: | GET
-- | --
https://mywebsite.com/apiCombinedData/?format=datatables
4.1.1
AttributeError
'RawQuerySet' object has no attribute 'count'
```

**Comment by matthewhegarty** [comment] 2022-10-04 11:59
Can you give us any more information?  Steps to reproduce, or a test case?

**Comment by matthewhegarty** [comment] 2022-10-04 12:00
Looks like a duplicate of [this](https://github.com/izimobil/django-rest-framework-datatables/issues/22#issuecomment-439392904)

**Comment by izimobil** [comment] 2022-11-16 14:06
Yes it's a duplicate of #22 , I'm closing the issue

**Closed by izimobil** 2022-11-16 14:06 UTC
